### PR TITLE
Added size check control

### PR DESCRIPTION
**Pull request by rifatdover**
On replace update null check done but did not chek if the new size equals to 0.

### CODE REVIEW

**Comment by rifatdover** [comment]
I signed it!

**Comment by rifatdover** [comment]
@yigit Can you check this?

**Comment by amrro** [comment]
I guess you intiate the adapter with data after creating it. So, what if you got no data from the api, or want to clear the recycler?

**Comment by rifatdover** [comment]
Forgive me if I have a lack of knowledge but I can not understand the relation between your question and the thing I do? What is made inside adapter is passing an update data to the adapter. If api or JsonMapping creates an object list with 0 items adapter will cause crash. And if we come to your question I will pass null or an object with 0 items and it will work.

**Pull request closed without merging**
